### ISSUE TITLE
какой хост надо вписывать

### ISSUE THREAD

**Issue by KinitoPET1998** [JetblockStudio/bedrockportal#14]
какой хост надо вписывать
![BedrockPortal - Multiplatform multiplayer for Minecraft Bedrock Edition 11 05 2024 11_44_38](https://github.com/JetblockStudio/bedrockportal/assets/169031652/e1c0d5ac-c851-4a27-9284-a0ea38cc5143)

**Comment by Poloni13** [comment]
Абсолютно любой это будет имя хоста которое  будут видеть все пользователи
